export const APPS_RECEIVE_START = 'APPS_RECEIVE_START'
export const APPS_RECEIVE_SUCCESS = 'APPS_RECEIVE_SUCCESS'
export const APPS_RECEIVE_FAILURE = 'APPS_RECEIVE_FAILURE'

export const CARD_COLOR_CHANGE_START = 'CARD_COLOR_CHANGE_START'
export const CARD_COLOR_CHANGE_SUCCESS = 'CARD_COLOR_CHANGE_SUCCESS'
export const CARD_COLOR_CHANGE_FAILURE = 'CARD_COLOR_CHANGE_FAILURE'