export const PROFILE_RECEIVE_START = 'PROFILE_RECEIVE_START'
export const PROFILE_RECEIVE_SUCCESS = 'PROFILE_RECEIVE_SUCCESS'
export const PROFILE_RECEIVE_FAILURE = 'PROFILE_RECEIVE_FAILURE'

export const PROFILE_EDIT_START = 'PROFILE_EDIT_START'
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS'
export const PROFILE_EDIT_FAILURE = 'PROFILE_EDIT_FAILURE'